version: "3.7"
services:
  backend:
    image: java-docker-application-jar
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: some-db
    ports:
      - '5432:5432'